
# File test-examples-safe_mean.R
# Generated by doctest: do not edit by hand

test_that("Example: safe_mean", {
  # Created from example for 'safe_mean', file /Users/david/doctest/tests/testthat/testPackage/R/safe-arithmetic.R line 9
  
  x <- 1:3
  expect_equals(safe_mean(x), 2)
})


test_that("safe-mean-errors", {
  # Created from example for 'safe_mean', file /Users/david/doctest/tests/testthat/testPackage/R/safe-arithmetic.R line 14
  expect_error(safe_mean("a"), "not numeric")
  expect_warning(safe_mean(c(1, NA)), "NA elements")
})

