
# File test-examples-safe_var.R
# Generated by doctest: do not edit by hand

test_that("Example: safe_var", {
  # Created from example for 'safe_var', file /Users/david/doctest/tests/testthat/testPackage/R/safe-arithmetic.R line 35
  
  x <- 1:5
  expect_length(safe_var(x), 1)
})

