
# File test-examples-add.R
# Generated by doctest: do not edit by hand

test_that("Example: add", {
  # Created from example for 'add', file /Users/david/doctest/tests/testthat/testPackage/R/safe-arithmetic.R line 54
  
  
  add(1, 2)
  expect_equals(1 + 1, add(1, 1))
})

