
# File test-examples-foo.R
# Generated by testygen: do not edit by hand

test_that("Example: foo", {
  # Created from example for 'foo', file <text> line 9
  
  foo(1)
  expect_equal(foo(2), 2)
})


test_that("test-abc", {
  # Created from example for 'foo', file <text> line 15
  expect_warning(foo("abc"))
  expect_equal(foo("abc"), NA)
})

