

#' @importFrom roxygen2 roclet_output
#' @export
roclet_output.roclet_doctest <- function (x, results, base_path, ...) {
  for (result in results) {
    contents <- test_file_contents(result)
    filename <- test_file_name(result)
    write_test_file(filename, contents, base_path = base_path)
  }
}


write_test_file <- function (filename, contents, base_path) {
  if (! missing(base_path)) {
    test_path <- file.path(pkgload::pkg_path(base_path), "tests", "testthat")
    test_file_path <- file.path(test_path, filename)
  } else {
    # prints to stdout
    test_file_path <- ""
  }
  cat(contents, file = test_file_path, sep = "\n", append = FALSE)
}


test_file_name <- function (result) {
  sprintf("test-examples-%s.R", result$object)
}


test_file_contents <- function (result) {
  lines <- ""
  test_file_name <- test_file_name(result)
  lines <- c(lines, sprintf("# File %s", test_file_name))
  lines <- c(lines, "# Generated by doctest: do not edit by hand")

  for (test in result$tests) {
    newlines <- build_lines(test)
    lines <- c(lines, newlines)
  }

  lines
}


build_lines <- function (test) {
  lines <- c(
             "",
             sprintf("test_that(\"%s\", {", test$name),
             sprintf("  # Created from example for '%s', file %s line %s",
                     test$source_object,
                     test$source_file,
                     test$source_line
                     ),
             paste0("  ", test$lines),
             "})",
             ""
            )

  return(lines)
}

