#' Write testthat tests and examples together
#'
#' Doctest lets you combine tests and examples. For more information, see
#' [@doctest] and [@expect].
#'
#' ```{r child = "man/rmd/example.Rmd"}
#' ```
#'
#' ```{r child = "man/rmd/usage.Rmd"}
#' ```
#'
#' Then run [roxygen2::roxygenize()] or [devtools::document()] from the
#' command line.
#'
#' Doctest is `r lifecycle::badge("experimental")`.
#'
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL


#' Create an expectation
#'
#' `@expect` creates an expectation for your example code.
#'
#' @details
#' Use `@expect` to create a testthat expectation.
#'
#'     #' @doctest
#'     #'
#'     #' @expect equals(4)
#'     #' 2 + 2
#'     #'
#'     #' f <- function () warning("Watch out")
#'     #' @expect warning()
#'     #' f()
#'
#' The next expression will be inserted as the first
#' argument to the `expect_*` call.
#'
#' Don't include the `expect_` prefix.
#'
#' If you want to include the expression in a different
#' place or places, use a dot `.`:
#'
#'     @expect equals(., rev(.))
#'     c("T", "E", "N", "E", "T")
#'
#' @name expect-tag
#' @aliases @expect
#' @family Expectations
NULL



#' Create a snapshot test
#'
#' `@snap` creates a
#' [snapshot test](https://testthat.r-lib.org/articles/snapshotting.html)
#' for your example. It is shorthand for `@expect snapshot()`.
#'
#' @details
#' Often, examples show complex output to the user. If this output changes,
#' you want to check that it still "looks right". Snapshot tests help by
#' failing when the output changes, and allowing you to review and approve
#' the new output.
#'
#'     #' @doctest
#'     #'
#'     #' @snap
#'     #' summary(lm(Petal.Width ~ Species, data = iris))
#'
#' @name snap-tag
#' @aliases @snap
#' @family Expectations
NULL



#' Add a line of code to the test
#'
#' `@testRaw` creates an expectation for your example code.
#'
#' @details
#' `@testRaw` adds an arbitrary line of code to your test.
#'
#'     #' @doctest
#'     #'
#'     #'x <- 2 + 2
#'     #' @testRaw skip_on_cran("This code will take too long")
#'     #' @expect equal(55)
#'     #' fibonacci(10)
#'
#' Unless your doctest has at least one [@expect] or [@expectRaw] tag, no test
#' will be created. So use those tags, not `@testRaw`, to add expectations.
#'
#' Remember that the main purpose of examples is to document your package for
#' your users. If your code is getting too different from your example, consider
#' splitting it off into a proper test file. You can do this by renaming it and
#' deleting the `Generated by doctest` comment.
#'
#' @name testRaw-tag
#' @aliases @testRaw
NULL


#' Create an expectation as-is
#'
#' `@expectRaw` creates an expectation for your example code, without adding
#' the next expression as the subject.
#'
#' @details
#' `@expectRaw` creates a testthat expectation. Unlike [@expect], it doesn't
#' insert the following expression inside the expectation:
#'
#'     #' @doctest
#'     #'
#'     #'x <- 2 + 2
#'     #' @expectRaw equals(x, 4)
#'     #'
#'     #' f <- function () warning("Watch out")
#'     #' @expectRaw warning(f())
#'
#' Don't include the `expect_` prefix.
#'
#' @name expectRaw-tag
#' @aliases @expectRaw
#' @family Expectations
NULL


#' Start a  doctest
#'
#' `@doctest` starts a doctest.
#'
#' @details
#' Use `@doctest` where you would usually use `@examples`. Then add
#' [@expect] and [@expectRaw] tags beneath it to create expectations.
#'
#' You can have more than one `@doctest` tag. Each doctest will create
#' a new test, but they will all be merged into a single Rd example.
#'
#' A test will only be written if your `@doctest` section has some
#' expectations in it. This lets you change `@examples` to `@doctest` without
#' generating unexpected tests.
#'
#' By default, a test labelled "Example: &lt;object name&gt;" is created. You
#' can put a different label after `@doctest`:
#'
#'     #' @doctest Positive numbers
#'     #'
#'     #' x <- 1
#'     #' @expect equal(x)
#'     #' abs(x)
#'     #'
#'     #' @doctest Negative numbers
#'     #' x <- -1
#'     #' @expect equal(-x)
#'     #' abs(x)
#
#' @name doctest-tag
#' @aliases @doctest
NULL


#' Exclude example code from a test
#'
#' `@omit` excludes code from a test until the next tag.
#' Use `@resume` to restart including code without creating an expectation.
#'
#' @details
#' Use `@omit` to avoid redundant or noisy code:
#'
#'     #' @doctest
#'     #'
#'     #' @expect equal(0)
#'     #' sin(0)
#'     #'
#'     #' @omit
#'     #' curve(sin(x), 0, 2 * pi)
#'     #'
#'     #' @expect equal(1)
#'     #' cos(0)
#'
#' `@omit` is separate from `\donttest` and `\dontrun` tags in Rd files. This
#' allows you to test code that would cause an error if run by R CMD CHECK. If
#' you also want R CMD CHECK to skip your code, you should use `\donttest{}`
#' separately (see [writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-R-documentation-files)).
#'
#' Remember that the main purpose of examples is to document your package for
#' your users. If your code is getting too different from your example, consider
#' splitting it off into a proper test file. You can do this by renaming it and
#' deleting the `Generated by doctest` comment.
#'
#' @name omit-tag
#' @aliases @omit @resume resume-tag
NULL
