#' Write testthat tests and examples together
#'
#' Doctest lets you combine tests and examples. For more information, see
#' [@doctest] and [@expect].
#'
#' @section Example:
#'
#' ```{r child = "example.Rmd"}
#' ```
#'
#' To use doctest in your package, add
#' ```r
#' Roxygen: list(roclets = c("collate", "rd", "namespace", "doctest::dt_roclet"))
#' ```
#' to the DESCRIPTION file. You may also optionally
#' add doctest to your 'Suggests:' dependencies.
#'
#' Then run [roxygen2::roxygenize()] or [devtools::document()] from the
#' command line.
#'
#' Doctest is `r lifecycle::badge("experimental")`.
#'
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL


#' Create an expectation
#'
#' `@expect` creates an expectation for your example code.
#'
#' @details
#' Use `@expect` to create a testthat expectation.
#'
#'     #' @examples
#'     #'
#'     #' @expect equals(4)
#'     #' 2 + 2
#'     #'
#'     #' f <- function () warning("Watch out")
#'     #' @expect warning()
#'     #' f()
#'
#' The next expression will be inserted as the first
#' argument to the `expect_*` call.
#'
#' Don't include the `expect_` prefix.
#'
#' If you want to include the expression in a different
#' place or places, use a dot `.`:
#'
#'     @expect equals(., rev(.))
#'     c("T", "E", "N", "E", "T")
#'
#' @name expect-tag
#' @aliases @expect
NULL


#' Create an expectation as-is
#'
#' `@expect` creates an expectation for your example code.
#'
#' @details
#' `@expectRaw` creates a testthat expectation. Unlike [@expect], it doesn't
#' insert the next expression:
#'
#'     #' @examples
#'     #'
#'     #'x <- 2 + 2
#'     #' @expectRaw equals(x, 4)
#'     #'
#'     #' f <- function () warning("Watch out")
#'     #' @expectRaw warning(f())
#'
#' Don't include the `expect_` prefix.
#'
#' @name expectRaw-tag
#' @aliases @expectRaw
NULL


#' Start a  doctest
#'
#' `@doctest` starts a doctest.
#'
#' @details
#' Use `@doctest` where you would usually use `@examples`. Then add
#' [@expect] and [@expectRaw] tags beneath it to create expectations.
#'
#' You can have more than one `@doctest` tag. Each doctest will create
#' a new test, but they will all be merged into a single Rd example.
#'
#' By default, a test labelled "Example: &lt;object name&gt;" is created. You
#' can put a different label after `@doctest`:
#'
#'     #' @doctest Positive numbers
#'     #'
#'     #' x <- 1
#'     #' @expect equal(x)
#'     #' abs(x)
#'     #'
#'     #' @doctest Negative numbers
#'     #' x <- -1
#'     #' @expect equal(-x)
#'     #' abs(x)
#
#' @name doctest-tag
#' @aliases @doctest
NULL


#' Exclude example code from a test
#'
#' `@skipTest` excludes code from a test until the next tag.
#' Use `@resumeTest` to restart including code without creating an expectation.
#'
#' @details
#' Use `@skipTest` to avoid redundant or noisy code:
#'
#'     #' @examples
#'     #'
#'     #' @expect equal(0)
#'     #' sin(0)
#'     #'
#'     #' @skipTest
#'     #' curve(sin(x), 0, 2 * pi)
#'     #'
#'     #' @expect equal(1)
#'     #' cos(0)
#'
#' Remember that the main purpose of examples is to document your package for
#' your users. If your code is getting too different from your example, consider
#' splitting it off into a proper test file. You can do this by renaming it and
#' deleting the `Generated by doctest` comment.
#'
#' @name skipTest-tag
#' @aliases @skipTest @resumeTest
NULL

